"""Initial migration

Revision ID: da92b11f80ab
Revises: 
Create Date: 2024-08-14 09:55:35.153810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da92b11f80ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memes_id'), 'memes', ['id'], unique=False)
    op.create_index(op.f('ix_memes_title'), 'memes', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memes_title'), table_name='memes')
    op.drop_index(op.f('ix_memes_id'), table_name='memes')
    op.drop_table('memes')
    # ### end Alembic commands ###
